{{- define "replicaNumber" -}}
{{- if .Values.storageclass.enableVolumeHA }}
{{- print 2 -}}
{{- else -}}
{{- print 1 -}}
{{- end -}}
{{- end -}}

{{- if .Values.storageclass.enabled -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ .Values.storageclass.default | quote }}
  name: hwameistor-storage-disk-{{ .Values.storageclass.diskType | lower}}
provisioner: disk.hwameistor.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: {{ .Values.storageclass.allowVolumeExpansion }}
reclaimPolicy: {{ .Values.storageclass.reclaimPolicy }}
parameters:
  diskType: {{ .Values.storageclass.diskType | quote}}
{{- end }}