apiVersion: v1
kind: Service
metadata:
  name: nginx-local-storage-lvm-svc
  labels:
    app: nginx-local-storage-lvm-sts
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None
  selector:
    app: nginx-local-storage-lvm-sts

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: nginx-local-storage-lvm-sts
spec:
  serviceName: "nginx"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-local-storage-lvm-sts
    spec:
      schedulerName: hwameistor-scheduler
      terminationGracePeriodSeconds: 10
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
      volumes:
        - name: www
          persistentVolumeClaim:
            claimName: local-storage-pvc-lvm

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-storage-pvc-lvm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-hdd-lvm
  resources:
    requests:
      storage: 1Gi

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-hdd-lvm
provisioner: lvm.hwameistor.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  replicaNumber: "1"
  poolClass: "HDD"
  poolType: "REGULAR"
  volumeKind: "LVM"
  striped: "true"
  csi.storage.k8s.io/fstype: "xfs"