apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: localdisknodes.hwameistor.io
spec:
  group: hwameistor.io
  names:
    kind: LocalDiskNode
    listKind: LocalDiskNodeList
    plural: localdisknodes
    shortNames:
    - ldn
    singular: localdisknode
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.freeCapacity
      name: FreeCapacity
      type: integer
    - jsonPath: .status.totalCapacity
      name: TotalCapacity
      type: integer
    - jsonPath: .status.totalDisk
      name: TotalDisk
      type: integer
    - jsonPath: .metadata.creationTimestamp
      name: age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: LocalDiskNode is the Schema for the localdisknodes API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: LocalDiskNodeSpec defines the desired state of LocalDiskNode
            properties:
              attachNode:
                description: AttachNode represent where disk is attached
                type: string
            required:
            - attachNode
            type: object
          status:
            description: LocalDiskNodeStatus defines the observed state of LocalDiskNode
            properties:
              disks:
                additionalProperties:
                  properties:
                    capacity:
                      description: Capacity
                      format: int64
                      type: integer
                    devPath:
                      description: DevPath
                      type: string
                    diskType:
                      description: DiskType SSD/HDD/NVME...
                      type: string
                    status:
                      description: Status
                      type: string
                  required:
                  - devPath
                  - diskType
                  - status
                  type: object
                description: Disks key is the name of LocalDisk
                type: object
              freeCapacity:
                description: FreeCapacity indicates the free capacity of all the disks
                format: int64
                type: integer
              freeDisk:
                description: FreeDisk
                format: int64
                type: integer
              pools:
                additionalProperties:
                  description: LocalPool is storage pool struct
                  properties:
                    class:
                      description: 'Supported class: HDD, SSD, NVMe'
                      enum:
                      - HDD
                      - SSD
                      - NVMe
                      type: string
                    disks:
                      items:
                        description: LocalDevice is disk struct
                        properties:
                          capacityBytes:
                            description: disk capacity
                            format: int64
                            type: integer
                          devPath:
                            description: e.g. /dev/sdb
                            type: string
                          state:
                            description: 'Possible state: Available, Inuse, Offline'
                            type: string
                          type:
                            description: 'Supported: HDD, SSD, NVMe, RAM'
                            type: string
                        type: object
                      type: array
                    freeCapacityBytes:
                      format: int64
                      type: integer
                    freeVolumeCount:
                      format: int64
                      type: integer
                    name:
                      description: 'Supported pool name: HDD_POOL, SSD_POOL, NVMe_POOL'
                      type: string
                    path:
                      description: VG path
                      type: string
                    totalCapacityBytes:
                      format: int64
                      type: integer
                    totalVolumeCount:
                      format: int64
                      type: integer
                    type:
                      default: REGULAR
                      description: 'Supported type: REGULAR'
                      enum:
                      - REGULAR
                      type: string
                    usedCapacityBytes:
                      format: int64
                      type: integer
                    usedVolumeCount:
                      format: int64
                      type: integer
                    volumeCapacityBytesLimit:
                      format: int64
                      type: integer
                    volumes:
                      items:
                        type: string
                      type: array
                  required:
                  - class
                  - freeCapacityBytes
                  - freeVolumeCount
                  - totalCapacityBytes
                  - totalVolumeCount
                  - type
                  - usedCapacityBytes
                  - usedVolumeCount
                  - volumeCapacityBytesLimit
                  type: object
                description: 'There may have multiple storage pools in a node. e.g.
                  HDD_POOL, SSD_POOL, NVMe_POOL Pools: poolName -> LocalPool'
                type: object
              state:
                description: 'State of the Local Storage Node/Member: New, Active,
                  Inactive, Failed'
                type: string
              totalCapacity:
                description: TotalCapacity indicates the capacity of all the disks
                format: int64
                type: integer
              totalDisk:
                description: TotalDisk
                format: int64
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
