apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: events.hwameistor.io
spec:
  group: hwameistor.io
  names:
    kind: Event
    listKind: EventList
    plural: events
    singular: event
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.resourceType
      name: type
      type: string
    - jsonPath: .spec.resourceName
      name: name
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Event is the Schema for the events API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: EventSpec defines the desired state of Event
            properties:
              records:
                items:
                  properties:
                    action:
                      type: string
                    actionContent:
                      type: string
                    result:
                      type: string
                    resultContent:
                      type: string
                    time:
                      format: date-time
                      type: string
                  type: object
                type: array
              resourceName:
                type: string
              resourceType:
                description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                  Important: Run "operator-sdk generate k8s" to regenerate code after
                  modifying this file Add custom validation using kubebuilder tags:
                  https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
                type: string
            required:
            - records
            - resourceName
            - resourceType
            type: object
          status:
            description: EventStatus defines the observed state of Event
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
