apiVersion: v1
kind: Pod
metadata:
  name: kafkaclient
  namespace: default
spec:
  containers:
  - name: kafka
    image: 10.6.170.180/uds/confluentinc-cp-kafka:5.0.1
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"