kind: Deployment
apiVersion: apps/v1
metadata:
  name: localstorage-local-storage-alerter
  namespace: local-storage-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstorage-local-storage-alerter
  template:
    metadata:
      labels:
        app: localstorage-local-storage-alerter
    spec:
      serviceAccount: storage-admin
      priorityClassName: system-cluster-critical
      containers:
        - name: main
          image: 10.6.170.180/localstorage/localstorage-local-storage-alerter:1.0-integrate_ldm_v1
          imagePullPolicy: Always
          args:
            - --debug=true
            - --is-virtual-machine=false
            - --namespace=$(POD_NAMESPACE)
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
