apiVersion: v1
kind: LimitRange
metadata:
  name: local-storage-system-limit-range
  namespace: local-storage-system
spec:
  limits:
  - default:
      cpu: 100m
      memory: 100Mi
    defaultRequest:
      cpu: 50m
      memory: 50Mi
    maxLimitRequestRatio:
      cpu: "2"
      memory: "2"
    type: Container