k8sImageRegistry: quay.io
hwameistorImageRegistry: ghcr.io
# Users in China can change to these sites for option
#k8sImageRegistry: quay.m.daocloud.io
#hwameistorImageRegistry: ghcr.m.daocloud.io

# StorageClass Settings
storageclass:
  # If enabled, a hwameistor storageclass will be created in your system
  enabled: true
  # If enabled, hwameistor storageclass will be a default storageclass in system
  # Attention: ensure your system doesn't have any default storageclass before
  # more info: https://kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/
  default: true
  # If allowed, volume can be expanded by modify pvc related field
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  # If set true, you need install drbd kernel module first
  enableVolumeHA: false
  # Represent which kind disk will be used to provision volume
  diskType: HDD
  fsType: xfs

scheduler:
  replicas: 1
  kubeApiServerConfigFilePath: /etc/kubernetes/admin.conf
  imageRepository: hwameistor/scheduler
  resources:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 100Mi

webhook:
  replicas: 1
  imageRepository: hwameistor/admission
  resources:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 100Mi

localDiskManager:
  tolerationsOnMaster: true
  enableCSI: true
  registrar:
    imageRepository: k8scsi/csi-node-driver-registrar
    tag: v1.1.0
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 5m
        memory: 5Mi
  manager:
    imageRepository: hwameistor/local-disk-manager
    resources:
      limits:
        cpu: 300m
        memory: 300Mi
      requests:
        cpu: 100m
        memory: 100Mi

localDiskManagerCSIController:
  replicas: 1
  provisioner:
    imageRepository: k8scsi/csi-provisioner
    tag: v2.0.3
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 5m
        memory: 5Mi
  attacher:
    imageRepository: k8scsi/csi-attacher
    tag: v3.0.1
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 5m
        memory: 5Mi

localStorage:
  tolerationsOnMaster: true
  registrar:
    imageRepository: k8scsi/csi-node-driver-registrar
    tag: v1.1.0
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 5m
        memory: 5Mi
  member:
    imageRepository: hwameistor/local-storage
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 5m
        memory: 5Mi

localStorageCSIController:
  replicas: 1
  provisioner:
    imageRepository: k8scsi/csi-provisioner
    tag: v2.0.3
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 5m
        memory: 5Mi
  attacher:
    imageRepository: k8scsi/csi-attacher
    tag: v3.0.1
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 5m
        memory: 5Mi
  resizer:
    imageRepository: k8scsi/csi-resizer
    tag: v1.0.1
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 5m
        memory: 5Mi
