name: Adaptation-test

on:
  workflow_dispatch:
    inputs:
      k8s-version:
        description: 'choice'
        required: true
        default: 'warning'
        type: choice
        options:
          - k8s1.25
          - k8s1.23

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: unit-test
        run: make unit-test
  k8s1_25-test:
    if: ${{ inputs.k8s-version == 'k8s1.25' }}
    runs-on: ["e2e"]
    timeout-minutes: 180
    steps:
      - name: delete
        run: |
          sudo rm -rf /github/actions-runner/_work/hwameistor/hwameistor/_build
          sudo rm -rf /github/actions-runner/_work/hwameistor/hwameistor/test/e2e/drbd-adapter/
          sudo rm -rf /home/github/actions-runner/_work/hwameistor/hwameistor/_build
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: e2e test
        env:
          E2E_TESTING_LEVEL: ${{ inputs.k8s-version }}
        run: make e2e-test
  k8s1_23-test:
    if: ${{ inputs.k8s-version == 'k8s1.23' }}
    runs-on: [ "e2e" ]
    timeout-minutes: 180
    steps:
      - name: delete
        run: |
          sudo rm -rf /github/actions-runner/_work/hwameistor/hwameistor/_build
          sudo rm -rf /github/actions-runner/_work/hwameistor/hwameistor/test/e2e/drbd-adapter/
          sudo rm -rf /home/github/actions-runner/_work/hwameistor/hwameistor/_build
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: e2e test
        env:
          E2E_TESTING_LEVEL: ${{ inputs.k8s-version }}
        run: make e2e-test

