name: Adaptation-test

on:
  workflow_dispatch:
    inputs:
      k8s-version:
        description: 'choice'
        required: true
        default: 'warning'
        type: choice
        options:
          - ALL
          - k8s1.25
          - k8s1.23
          - centos7.6
          - centos8.1
          - ubuntu2204
          - kylin10_arm
          - centos7.9_offline

jobs:
  k8s1_25-test:
    if: ${{ inputs.k8s-version == 'k8s1.25' || inputs.k8s-version == 'ALL'  }}
    runs-on: ["e2e"]
    timeout-minutes: 180
    steps:
      - name: delete
        run: |
          sudo rm -rf /github/actions-runner/_work/hwameistor/hwameistor/_build
          sudo rm -rf /github/actions-runner/_work/hwameistor/hwameistor/test/e2e/drbd-adapter/
          sudo rm -rf /home/github/actions-runner/_work/hwameistor/hwameistor/_build
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: e2e test
        env:
          E2E_TESTING_LEVEL: ${{ inputs.k8s-version }}
        run: make e2e-test
  k8s1_23-test:
    if: ${{ inputs.k8s-version == 'k8s1.23'|| inputs.k8s-version == 'ALL'   }}
    runs-on: [ "vsphere" ]
    timeout-minutes: 180
    steps:
      - name: delete
        run: |
          sudo rm -rf /github/actions-runner/_work/hwameistor/hwameistor/_build
          sudo rm -rf /github/actions-runner/_work/hwameistor/hwameistor/test/e2e/drbd-adapter/
          sudo rm -rf /home/github/actions-runner/_work/hwameistor/hwameistor/_build
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: e2e test
        env:
          E2E_TESTING_LEVEL: ${{ inputs.k8s-version }}
        run: make e2e-test
  c81-test:
    if: ${{ inputs.k8s-version == 'centos8.1' || inputs.k8s-version == 'ALL'  }}
    runs-on: ["e2e"]
    timeout-minutes: 180
    steps:
      - name: delete
        run: |
          sudo rm -rf /github/actions-runner/_work/hwameistor/hwameistor/_build
          sudo rm -rf /github/actions-runner/_work/hwameistor/hwameistor/test/e2e/drbd-adapter/
          sudo rm -rf /home/github/actions-runner/_work/hwameistor/hwameistor/_build
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: e2e test
        env:
          E2E_TESTING_LEVEL: "k8sc81"
        run: make e2e-test
  u2204-test:
    if: ${{ inputs.k8s-version == 'ubuntu2204' || inputs.k8s-version == 'ALL'   }}
    runs-on: ["e2e"]
    timeout-minutes: 180
    steps:
      - name: delete
        run: |
          sudo rm -rf /github/actions-runner/_work/hwameistor/hwameistor/_build
          sudo rm -rf /github/actions-runner/_work/hwameistor/hwameistor/test/e2e/drbd-adapter/
          sudo rm -rf /home/github/actions-runner/_work/hwameistor/hwameistor/_build
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: e2e test
        env:
          E2E_TESTING_LEVEL: "k8su2204"
        run: make e2e-test
  kylin10_arm-test:
    if: ${{ inputs.k8s-version == 'kylin10_arm' || inputs.k8s-version == 'ALL'  }}
    runs-on: ["e2e"]
    timeout-minutes: 180
    steps:
      - name: delete
        run: |
          sudo rm -rf /github/actions-runner/_work/hwameistor/hwameistor/_build
          sudo rm -rf /github/actions-runner/_work/hwameistor/hwameistor/test/e2e/drbd-adapter/
          sudo rm -rf /home/github/actions-runner/_work/hwameistor/hwameistor/_build
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: e2e test
        env:
          E2E_TESTING_LEVEL: "kylin10_arm"
          E2E_VERSION: "ARM"
        run: make e2e-test
  centos7_6_offline-test:
    if: ${{ inputs.k8s-version == 'centos7.9_offline' || inputs.k8s-version == 'ALL'  }}
    runs-on: ["e2e"]
    timeout-minutes: 180
    steps:
      - name: delete
        run: |
          sudo rm -rf /github/actions-runner/_work/hwameistor/hwameistor/_build
          sudo rm -rf /github/actions-runner/_work/hwameistor/hwameistor/test/e2e/drbd-adapter/
          sudo rm -rf /home/github/actions-runner/_work/hwameistor/hwameistor/_build
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: e2e test
        env:
          E2E_TESTING_LEVEL: "centos7.9_offline"
        run: make e2e-test