name: Period check
on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  e2e-test:
    runs-on: ["self-hosted"]
    timeout-minutes: 180
    steps:
      - name: delete
        run: |
          sudo rm -rf /github/actions-runner/_work/hwameistor/hwameistor/_build
          sudo rm -rf /github/actions-runner/_work/hwameistor/hwameistor/test/e2e/drbd-adapter/
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: e2e test
        env:
          E2E_TESTING_LEVEL: "periodCheck"
        run: make e2e-test
