name: HwameiStor PR

on:
  pull_request:
    branches:
      - main
    paths:
      - "pkg/*"

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: unit-test
        run: make unit-test
