name: Period check
on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  relk8s-test:
    runs-on: ["vsphere"]
    timeout-minutes: 600
    steps:
      - name: delete
        run: |
          sudo rm -rf /github/actions-runner/_work/hwameistor/hwameistor/_build
          sudo rm -rf /github/actions-runner/_work/hwameistor/hwameistor/test/e2e/drbd-adapter/
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: relk8s test
        run: |
          relok8s chart move helm/hwameistor/ --image-patterns helm/hwameistor/.relok8s-images.yaml  --registry 172.30.45.210 --repo-prefix hwameistor -y
